"""Chat analysis: turn the raw extraction into a qualification report.

Reads the JSONL written by the extraction stage, aggregates per-chat counts,
and applies the selection criteria. This stage is separate from extraction and
is safe to re-run with different thresholds; it never modifies raw data.

No message text is ever emitted, to the terminal or to the report files.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Mapping, Optional, Sequence

from .selection import (
    ChatStats,
    Decision,
    SelectionCriteria,
    aggregate_chat_stats,
    descriptor_from_manifest_entry,
    evaluate_chat,
)
from .storage import chat_jsonl_path, iter_records, load_manifest

REPORT_JSON_NAME = "chat_analysis.json"
REPORT_MARKDOWN_NAME = "chat_analysis.md"


def analyse_chats(
    manifest: Mapping,
    chats_dir: Path,
    criteria: Optional[SelectionCriteria] = None,
) -> list[tuple[ChatStats, Decision]]:
    """Aggregate and evaluate every extracted chat in the manifest."""
    criteria = criteria or SelectionCriteria()
    results: list[tuple[ChatStats, Decision]] = []

    for entry in manifest.get("chats", {}).values():
        descriptor = descriptor_from_manifest_entry(entry)
        records = iter_records(chat_jsonl_path(chats_dir, descriptor.chat_id))
        stats = aggregate_chat_stats(
            descriptor, records, extraction_complete=entry.get("extraction_complete", True)
        )
        results.append((stats, evaluate_chat(stats, criteria)))

    results.sort(key=lambda pair: pair[0].my_text_messages, reverse=True)
    return results


def build_report(
    manifest: Mapping,
    results: Sequence[tuple[ChatStats, Decision]],
    criteria: Optional[SelectionCriteria] = None,
) -> dict:
    """Build the report structure. Pure: no I/O, no message text."""
    criteria = criteria or SelectionCriteria()

    chats = []
    qualifying_my_text = 0
    for stats, decision in results:
        row = stats.to_dict()
        row["qualifies"] = decision.included
        row["reasons"] = list(decision.reasons)
        chats.append(row)
        if decision.included:
            qualifying_my_text += stats.my_text_messages

    skipped = [
        {
            "chat_id": entry.get("chat_id"),
            "name": entry.get("name", ""),
            "chat_type": entry.get("chat_type", ""),
            "reason": entry.get("reason", ""),
        }
        for entry in manifest.get("skipped", {}).values()
    ]

    return {
        "window": {
            "target_year": manifest.get("target_year"),
            "timezone": manifest.get("timezone"),
            "window_start_utc": manifest.get("window_start_utc"),
            "window_end_utc": manifest.get("window_end_utc"),
        },
        "criteria": {
            "max_participants": criteria.max_participants,
            "min_my_text_messages": criteria.min_my_text_messages,
        },
        "totals": {
            "chats_extracted": len(chats),
            "chats_qualifying": sum(1 for row in chats if row["qualifies"]),
            "dialogs_skipped": len(skipped),
            "messages_extracted": sum(row["total_messages"] for row in chats),
            "my_text_messages_total": sum(row["my_text_messages"] for row in chats),
            "my_text_messages_in_qualifying_chats": qualifying_my_text,
        },
        "chats": chats,
        "skipped_dialogs": skipped,
    }


def _escape_cell(value: str) -> str:
    """Make a value safe for a markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", " ")


def _short_date(stamp: Optional[str]) -> str:
    return stamp[:10] if stamp else "-"


def render_markdown(report: Mapping) -> str:
    """Render the detailed report as markdown. Pure, and contains no message text."""
    window = report.get("window", {})
    criteria = report.get("criteria", {})
    totals = report.get("totals", {})

    lines = [
        "# Chat analysis report",
        "",
        "Generated by the analysis stage from the raw extraction. "
        "Counts only - this report never contains message text.",
        "",
        "## Window",
        "",
        f"- Target year: {window.get('target_year')} ({window.get('timezone')})",
        f"- UTC range: {window.get('window_start_utc')} to {window.get('window_end_utc')}",
        "",
        "## Criteria",
        "",
        f"- Maximum participants (groups only): {criteria.get('max_participants')}",
        f"- Minimum text messages authored by me: {criteria.get('min_my_text_messages')}",
        "",
        "## Totals",
        "",
        f"- Chats extracted: {totals.get('chats_extracted')}",
        f"- Chats qualifying: {totals.get('chats_qualifying')}",
        f"- Dialogs skipped before extraction: {totals.get('dialogs_skipped')}",
        f"- Messages extracted: {totals.get('messages_extracted')}",
        f"- My text messages (all chats): {totals.get('my_text_messages_total')}",
        f"- My text messages (qualifying chats): "
        f"{totals.get('my_text_messages_in_qualifying_chats')}",
        "",
        "## Chats",
        "",
        "| Chat | Type | Participants | My text msgs | My msgs | Total msgs | First | Last | Qualifies | Reasons |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |",
    ]

    for row in report.get("chats", []):
        participants = row.get("participant_count")
        participants_cell = str(participants) if row.get("participant_count_known") and participants is not None else "unknown"
        lines.append(
            "| {name} | {ctype} | {participants} | {mytext} | {mymsgs} | {total} | {first} | {last} | {ok} | {reasons} |".format(
                name=_escape_cell(row.get("name", "")),
                ctype=row.get("chat_type", ""),
                participants=participants_cell,
                mytext=row.get("my_text_messages", 0),
                mymsgs=row.get("my_messages", 0),
                total=row.get("total_messages", 0),
                first=_short_date(row.get("first_message_utc")),
                last=_short_date(row.get("last_message_utc")),
                ok="yes" if row.get("qualifies") else "no",
                reasons=_escape_cell("; ".join(row.get("reasons", []))) or "-",
            )
        )

    skipped = report.get("skipped_dialogs", [])
    if skipped:
        lines += [
            "",
            "## Dialogs skipped before extraction",
            "",
            "| Chat | Type | Reason |",
            "| --- | --- | --- |",
        ]
        for row in skipped:
            lines.append(
                "| {name} | {ctype} | {reason} |".format(
                    name=_escape_cell(row.get("name", "")),
                    ctype=row.get("chat_type", ""),
                    reason=_escape_cell(row.get("reason", "")),
                )
            )

    return "\n".join(lines) + "\n"


def render_terminal_summary(report: Mapping, limit: int = 25) -> str:
    """Render a compact console summary. Contains no message text."""
    totals = report.get("totals", {})
    chats = report.get("chats", [])

    lines = [
        "",
        "Chat analysis",
        "-------------",
        f"  chats extracted : {totals.get('chats_extracted')}",
        f"  chats qualifying: {totals.get('chats_qualifying')}",
        f"  messages        : {totals.get('messages_extracted')}",
        f"  my text msgs    : {totals.get('my_text_messages_total')} "
        f"({totals.get('my_text_messages_in_qualifying_chats')} in qualifying chats)",
        "",
        f"  {'chat':<32} {'type':<11} {'members':>7} {'my text':>8}  qualifies",
    ]

    for row in chats[:limit]:
        name = str(row.get("name", ""))
        if len(name) > 32:
            name = name[:29] + "..."
        participants = row.get("participant_count")
        members = str(participants) if row.get("participant_count_known") and participants is not None else "?"
        lines.append(
            f"  {name:<32} {row.get('chat_type', ''):<11} {members:>7} "
            f"{row.get('my_text_messages', 0):>8}  {'yes' if row.get('qualifies') else 'no'}"
        )

    if len(chats) > limit:
        lines.append(f"  ... and {len(chats) - limit} more (see the full report)")

    return "\n".join(lines) + "\n"


def write_report(report: Mapping, processed_dir: Path) -> tuple[Path, Path]:
    """Write the JSON and markdown reports into the git-ignored processed dir."""
    processed_dir.mkdir(parents=True, exist_ok=True)

    json_path = processed_dir / REPORT_JSON_NAME
    markdown_path = processed_dir / REPORT_MARKDOWN_NAME

    with json_path.open("w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)

    markdown_path.write_text(render_markdown(report), encoding="utf-8")

    return json_path, markdown_path


def load_manifest_or_fail(manifest_path: Path) -> dict:
    manifest = load_manifest(manifest_path)
    if manifest is None:
        raise RuntimeError(
            f"No extraction manifest at {manifest_path}. Run the extraction stage first."
        )
    return manifest
